DEV/req135/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('example', views.template_example, name='example'),
    path('about', views.about, name='about'),
    path('issues', views.listAllIssues, name='issues'),
    path('issues/open', views.listOpenIssues, name='openIssues'),
    path('issues/closed', views.listClosedIssues, name='closedIssues'),
]

DEV/req135/gitnub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

DEV/req135/app/models.py
from django.contrib import admin
from django.db import models
from datetime import datetime
# Create your models here.

class LocalRepo(models.Model):
    url = models.CharField(max_length=255, unique=True)
    path = models.CharField(max_length=255, unique=True)
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Last Updated')

DEV/req135/app/views.py
from django.http.request import HttpRequest
from django.shortcuts import redirect, render, HttpResponse
from pydriller import Repository
from git.repo import Repo
import logging
from . import gitlab
from . import utils


logger = logging.getLogger(__name__)
# Create your views here.
# Don't forget to route to your views in app/urls.py!

# route: / 
def index(request):
    return render(request, 'app/index.html')

# route: /example
def template_example(request):
    text = "This is a Django template example"
    data = ["Try", "Out", "This", "For", "Loop"]
    return render(request, 'app/example.html', {'text': text, 'data': data})

# route: /about
def about(request):
    return render(request, 'app/about.html')

def listAllIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues()
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)
    # Waiting for design and arch input
    # return HttpResponse("Waiting for design and arch input")
    return render(request, 'app/issues.html', {'issues': issues})

def listOpenIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues(state='opened')
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)
    # Waiting for design and arch input
    # return HttpResponse("Waiting for design and arch input")
    return render(request, 'app/issues.html', {'issues': issues})

def listClosedIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues(state='closed')
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)
    # Waiting for design and arch input
    # return HttpResponse("Waiting for design and arch input")
    return render(request, 'app/issues.html', {'issues': issues})

DEV/req135/app/templates/app/about.html
{% extends 'app/base.html' %}

{% block title %}About - GitNub{% endblock title %}

{% block app %}
<h1>WIP - Build about team here!</h1>
{% endblock app %}

DEV/req135/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GitNub{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/bootstrap.min.css' %}">
</head>
<body>
    <div class="wrapper">
        <div class="navbar navbar-light bg-light navbar-fixed-top shadow">
            <img class="navbar-brand" src="{% static 'app/logo.png' %}" alt="GitNub Logo" width="250px" height="auto">
        </div>
        <div class="fill">
            <div class="sidebar">
                <nav class="nav bg-light">
                    <a href="{% url 'app:index' %}" class="nav-link">Home</a>                   
                    <a href="{% url 'app:example' %}" class="nav-link">Example</a>
                    <a href="{% url 'app:about' %}" class="nav-link">About</a>
                    <a href="{% url 'app:issues' %}" class="nav-link">Issues</a>
                    <a href="{% url 'app:openIssues' %}" class="nav-link">Open Issues</a>
                    <a href="{% url 'app:closedIssues' %}" class="nav-link">Closed Issues</a>
                </nav>
            </div>
            <div id="app">{% block app %}{% endblock %}</div>
        </div>
    </div>
</body>
</html>

DEV/req135/app/templates/app/error.html
{% extends "app/base.html" %}

{% block app %}
<h1>Error</h1>
<p>{{ message }}</p>
{% endblock %}

DEV/req135/app/templates/app/example.html
{% extends "app/base.html" %}

{% block title %}Example - GitNub{% endblock %}

{% block app %}
<h1>{{ text }}</h1>

<ul>
    {% for sentence in data %}
        <li>{{ sentence }}</li>
    {% endfor %}
</ul>
{% endblock %}

DEV/req135/app/templates/app/index.html
{% extends "app/base.html" %}

{% block title %}Home - GitNub{% endblock %}

{% block app %}
<h1>Welcome to the development server!</h1>
{% endblock %}

DEV/req135/app/templates/app/issues.html
{% extends "app/base.html" %}

{% block title %}Issues{% endblock %}

{% block app %}
<h1>{{ text }}</h1>

<ul>
    {% for issue in issues %}
        <li>{{ issue.title }}</li>
    {% endfor %}
</ul>
{% endblock %}