PROD/current/app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('members', views.listMembers, name='members'),
    path('active', views.listActiveMembers, name='activeMembers'),
    re_path(r'^repository/(?P<full_slug>(.*))', views.repository, name='files'),
    path('member/<str:username>/commits', views.listMemberCommits, name='memberCommits'),
    path('commits', views.commitList, name='commits'),
    path('issues', views.listAllIssues, name='issues'),
    path('issues/open', views.listOpenIssues, name='openIssues'),
    path('issues/closed', views.listClosedIssues, name='closedIssues'),
    path('branches', views.branches, name='branches'),
    path('most_changed', views.mostChanged, name='mostChanged'),
    re_path(r'^history/(?P<path>(.*))', views.modList, name="history"),
]

PROD/current/gitnub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

PROD/current/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/css/base.css' %}">
    {% block css %}
    {% endblock css %}
    <title>{% block title %}GitNub{% endblock title %}</title>
</head>

<body>
    <header>
        <nav>
            {% block navbar %}
            <div class="nav-bar">
                <div class="select-page">
                    <a href="{% url 'app:index' %}">
                        <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
                    </a>
                    <ul class="project-info">
                        <li class="main-selection">Project Information</li>
                        <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
                    </ul>

                    <ul class="repository">
                        <li class="main-selection">Repository</li>
                        <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
                        <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
                        <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
                        <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
                    </ul>

                    <ul class="issues">
                        <li class="main-selection">Issues</li>
                        <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
                    </ul>
                </div>
            </div>
            {% endblock navbar %}
        </nav>

    </header>

    <main>{% block app %}{% endblock app %}</main>

PROD/current/app/templates/app/branches.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/branches.css' %}">
{% endblock css %}

{% block title %}Branches{% endblock title %}

{% comment %} {% block navbar %}
<div id="menu">
    <div class="select-page">
        <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a>Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %} {% endcomment %}

{% block app %}
<div id="branches">
    <div id="nav_bar">
        <div class="left">
            <h2>GitNub > </h2>
            <h2 style="font-weight:500;"><a href="branches.html">Branches</a></h2>
        </div>

        <div class="right">
            <div class="search button"> <!-- SEARCH BAR -->
                <img src="{% static 'app/assets/search.svg' %}" alt="search">
                <input type="text" placeholder="Search">
            </div>

            <div class="name button"> <!-- ORDENAR POR NOME OU POR ULTIMO BRANCH ATUALIZADO-->
                <a href="#">Name</a>
            </div>
        </div>
    </div>

    <!-------------------- GRID DOS BRANCHES EXISTENTES ------------------>
    <div id="active-branches">
        <h1>Active Branches</h1>
        <div id="select-branch">
            {% for branch in branches  %}
            <div class="branch">
                <a>
                    <div class="icon">
                        <svg width="31" height="37" viewBox="0 0 31 37" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M12.9167 6.45701C12.917 7.94586 12.4029 9.38908 11.4614 10.5424C10.5199 11.6958 9.20877 12.4884 7.75001 12.7862V18.082H19.375C20.4027 18.082 21.3883 17.6737 22.115 16.947C22.8417 16.2203 23.25 15.2347 23.25 14.207V12.7862C21.6819 12.4661 20.2884 11.5751 19.3399 10.286C18.3913 8.99696 17.9552 7.40158 18.116 5.80921C18.2769 4.21684 19.0233 2.74093 20.2105 1.6676C21.3977 0.594273 22.9412 3.58774e-06 24.5417 3.58774e-06C26.1421 3.58774e-06 27.6856 0.594273 28.8728 1.6676C30.06 2.74093 30.8064 4.21684 30.9673 5.80921C31.1281 7.40158 30.692 8.99696 29.7435 10.286C28.7949 11.5751 27.4015 12.4661 25.8333 12.7862V14.207C25.8333 15.0551 25.6663 15.8949 25.3417 16.6785C25.0172 17.4621 24.5414 18.174 23.9417 18.7737C23.342 19.3734 22.6301 19.8492 21.8465 20.1737C21.0629 20.4983 20.2231 20.6653 19.375 20.6653H7.75001V23.3778C9.31814 23.6979 10.7116 24.5889 11.6601 25.878C12.6087 27.167 13.0448 28.7624 12.884 30.3548C12.7231 31.9472 11.9767 33.4231 10.7895 34.4964C9.60228 35.5697 8.05882 36.164 6.45834 36.164C4.85787 36.164 3.31441 35.5697 2.12719 34.4964C0.939973 33.4231 0.19358 31.9472 0.0327185 30.3548C-0.128143 28.7624 0.307985 27.167 1.25655 25.878C2.20512 24.5889 3.59854 23.6979 5.16668 23.3778V12.7862C3.96941 12.5418 2.86604 11.9627 1.98473 11.1163C1.10341 10.2699 0.480308 9.19078 0.187792 8.00435C-0.104725 6.81793 -0.0546529 5.57286 0.332193 4.41376C0.719039 3.25465 1.42678 2.22908 2.37323 1.45615C3.31967 0.683221 4.46597 0.194656 5.679 0.0471992C6.89202 -0.100258 8.12199 0.0994442 9.22605 0.623111C10.3301 1.14678 11.2629 1.97292 11.9162 3.00558C12.5695 4.03825 12.9164 5.23506 12.9167 6.45701Z"
                                fill="black" />
                        </svg>
                    </div>
                    <div class="text">
                        <h1>{{ branch.title }}</h1> <!-- Nome do branch -->
                        <div id="info">
                            <div class="info 1">
                                <h3>Last Update</h3>
                                <h2>{{ branch.ldate }}</h2>
                            </div>
                            <div class="info 2">
                                <h3>Updated by</h3>
                                <h2>{{ branch.lupdater }}</h2>
                            </div>

                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <!-------------------- BOTÃO BACK ------------------>
        <div id="back_button">
            <p>Back</p>
        </div>
    </div>
</div>
{% endblock app %}

PROD/current/app/templates/app/commits.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/commits.css' %}">
{% endblock css %}

{% comment %} {% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a>Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %} {% endcomment %}

{% block app %}
<div class="top-info">
    <div class="view">
    	<a href="{ url 'app:index' }">GitNub ></a>
        <a>Commits</a>
    </div>

    <div class="buttons">
        {% comment %} <div class="timeline button">
            <a>Timeline</a>
        </div> {% endcomment %}
    </div>
</div>

{% comment %} <h5 class="date">November 19th 2021</h5> {% endcomment %}
{% for commit in commits %}
<div class="day">
    <div class="commit">
        {% if commit.css %}
        <div class="circle {{ commit.css }}">
        {% else %}
        <div class="circle">
        {% endif %}
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>{{ commit.msg }}</h4>
            <p>{{ commit.author }}<span>{{ commit.date | date }}</span></p>
        </div>
    </div>
</div>
{% endfor %}


{% endblock app %}

PROD/current/app/templates/app/error.html
{% extends "app/base.html" %}

{% block app %}
<h1>Error</h1>
<p>{{ message }}</p>
{% endblock %}

PROD/current/app/templates/app/file.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
{% if markdown %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/github-markdown.css' %}">
{% endif %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/file.css' %}">
{% endblock css %}

{% block title %}{{filename}}{% endblock title %}

{% block app %}
<div id="file">
    <!-------------------- BARRA DE CIMA ------------------>
    <div id="nav_bar">
        <div class="left">
            <h2>GitNub > </h2>
            <h2><a href="{% url 'app:files' '' %}">Repository ></a></h2>
            {% for dir, redirect in paths %}
            <h2><a href="{% url 'app:files' redirect %}">{{dir}} ></a></h2>
            {% endfor %}
            <h2 style="font-weight:500;"><a>{{ filename }}</a></h2>
        </div>
        <div class="right">
            <div class="history button">
                <a href="{% url 'app:history' slug %}">History</a>
            </div>
        </div>
    </div>

    <div id="upload">
        {% comment %}
        <div class="profile">
            <!-- CAIXA 1 -->
            <div class="foto des"> <!-- neste caso o ret está na label de design -->
                <img src="" alt="profile picture">
            </div>
            <div class="creator">
                <div class="file-name">{{ filename }}</div>
                <a href="proj-info-members-select.html">
                    <div class="author">Author Name</div>
                </a>
            </div>
        </div>
        {% endcomment %}
        <div class="file-container">
            <!-- CAIXA  -->
            <div class="name">
                <div class="square" id="des">
                    <svg width="36" height="36" viewBox="0 0 36 36" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <path d="M36 0H0V35.8945H36V0Z" />
                        <path
                            d="M18.0017 22.5626C20.5592 22.5626 22.6325 20.4954 22.6325 17.9454C22.6325 15.3953 20.5592 13.3281 18.0017 13.3281C15.4441 13.3281 13.3708 15.3953 13.3708 17.9454C13.3708 20.4954 15.4441 22.5626 18.0017 22.5626Z"
                            fill="white" />
                    </svg>
                </div>
                <div class="tile">{{ filename }}</div>

            </div>
            {% if markdown %}
            <div class="content markdown-body">
            {% else %}
            <div class="content">
            {% endif %}
                {{ data | safe }}
            </div>
        </div>
    </div>

    {% comment %}
    <div id="active-issues">
        <div class="issues-top-bar">
            <div class="left button">Associated Active Issues</div>
            <div class="right button">Details</div>
        </div>

        <div class="issue-grid">
            <div class="issue">
                <a href="">
                    <div class="foto des">
                        <img src="img/porfile.svg" alt="profile picture">
                    </div>
                    <div class="text">
                        <h1>Issue #00</h1>
                        <div id="info">
                            <div class="info one">
                                <h3>Created</h3>
                                <h2>0 hours ago</h2>
                            </div>
                            <div class="info two">
                                <h3>by</h3>
                                <h2>Author Name</h2>
                            </div>

                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    {% endcomment %}

    <!-------------------- BOTÃO BACK ------------------>
    <div id="back_button">
        <p>Back</p>
    </div>
</div>
{% endblock app %}

PROD/current/app/templates/app/history.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/issues.css' %}">
{% endblock css %}

{% block title %}History{% endblock title %}

{% block app %}
<div class="top-info">
    <div class="view">
        <a href={% url 'app:index' %}>GitNub ></a>
        <a>History</a>
    </div>
</div>

<div class="issues-list">
    {% for mod in data %}
    <div class="issue">
        <div class="text">
            <h4>{{ mod.type | capfirst }}</h4>
            <p>{{ mod.add }} line{{ mod.add | pluralize }} added, {{ mod.del }} line{{ mod.add | pluralize }} deleted</p>
            <p><span>By {{ mod.author }} on </span><span>{{ mod.date | date }}</span></p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock app %}

PROD/current/app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/index.css' %}">
{% endblock css %}

{% block title %}Index - GitNub{% endblock %}

{% block app %}
<img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="">
<h1>Welcome to GitNub!</h1>
{% endblock %}

PROD/current/app/templates/app/issues.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/issues.css' %}">
{% endblock css %}

{% block title %}GitNub{% endblock title %}

{% comment %} {% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a>Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %} {% endcomment %}

{% block app %}
<div class="top-info">
    <div class="view">
	<a href="{ url 'app:index' }">GitNub ></a>
        <a>Issues</a>
    </div>

    <div class="buttons">
        <div class="order-by button">
            <a href="">Order By</a>
        </div>
    </div>
</div>

{% block state %}{% endblock state %}

<div class="issues-list">

    {% for issue in issues %}
    <div class="issue">
        <div class="circle arch">
            <img src=" {% comment "TODO" %}{% endcomment %}">
        </div>
        <div class="text">
            <h4>{{ issue.title }}</h4>
            <p>By {{ issue.authorn }} at {{ issue.cd }}</p>
            <p>{{ issue.cd | timesince }} ago</p>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock app %}

PROD/current/app/templates/app/list.html
{% extends 'app/base.html' %}

{% block title %}Commits by {{ name }} - GitNub{% endblock title %}


{% block app %}
<form method="get">
    {{form}}
</form>
<h1>List of commits made by {{name}}</h1>
<ul>
    {% for commit in commits %}
        <li>{{ commit }}</li>
    {% endfor %}
</ul>
{% endblock app %}

PROD/current/app/templates/app/members.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/members.css' %}">
{% endblock css %}

{% comment %}
{% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a>Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}
{% endcomment %}

{% block app %}
<div class="top-info">
    <div class="view">
        <a href="">GitNub ></a>
        <a href="">Project Information ></a>
        <a href="">Members</a>
    </div>

    <div class="buttons">
        <div class="order-by button">
            <a>Order by</a>
        </div>
    </div>
</div>
<div class="members-list">

    {% for member in members %}
        <a>
            <div class="member {{ member.css }}">
                <div class="square-gitnub">
                    <div class="square">
                        <div class="circle"></div>
                    </div>
                </div>
                <div class="text">
                    <h4>{{ member.name }}</h2>
                    <h5>{{ member.role }}</h5>
                </div>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock app %}

PROD/current/app/templates/app/modifications.html
{% extends 'app/base.html' %}

{% block title %}History{% endblock %}

{% block app %}
<h1>{{ text }}</h1>

<ul>
    {% for commit in data %}
        <li>{{ commit.file }} {{ commit.type }} by {{ commit.author }} on {{ commit.date | date }} ({{ commit.add }} lines added, {{ commit.del }} lines deleted) </li>
        {% comment %} <li>{{ commit }}</li> {% endcomment %}
        {% endfor %}
</ul>
{% endblock app %}

PROD/current/app/templates/app/openIssues.html
{% extends 'app/issues.html' %}

{% block state %}
<div class="issue-state">
    <div class="all select">
        <a href="{% url 'app:issues' %}">All</a>
    </div>

    <div class="open select">
        <a>Open</a>
    </div>

    <div class="closed select">
        <a href="{% url 'app:closedIssues' %}">Closed</a>
    </div>
</div>
{% endblock state %}

PROD/current/app/templates/app/repository.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/repository.css' %}">
{% endblock css %}

{% comment %} {% block navbar %}
<div id="menu">
    <div class="select-page">
        <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            {% if paths %}
                <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            {% else %}
                <li class="hidden-selection"><a>Files</a></li>
            {% endif %}
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection">Lists</li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %} {% endcomment %}

{% block app %}
<div id="repository">
    <div id="nav_bar">
        <div class="left">
            <h2>GitNub > </h2>
            {% if paths %}
                <h2><a href="{% url 'app:files' '' %}">Repository ></a></h2>
                {% for dir, redirect in paths %}
                <h2><a href="{% url 'app:files' redirect %}">{{dir}} ></a></h2>
                {% endfor %}
                <h2 style="font-weight:500;"><a>{{ filename }}</a></h2>
            {% else %}
                <h2 style="font-weight:500;">Repository</h2>
            {% endif %}
        </div>

        <div class="right">
            {% comment %} <div class="name button">
                <a>Name</a>
            </div> {% endcomment %}

            <div class="history button">
                <a href={% url 'app:commits' %}>History</a>
            </div>
        </div>
    </div>

    <div id="branches">
        <div class="select-branch"><p>Branch</p></div>
        <div class="select-branch location"><p>main</p></div>
    </div>

    <div id="rep_files">
        {% for file in data %}
            <div class="rep">
                <a href="{% url 'app:files' file.url %}">
                    <div class="square">
                        <img src="{% static 'app/assets/file.svg' %}" alt="">
                    </div>
                    <div class="text">
                        <h1>{{ file.name }}</h1>
                        <div id="info">
                            {% comment %}
                                <div class="info 1">
                                    <h3>Last commit by</h3>
                                    <h2>Lorem Ipsum</h2>
                                </div>
                                <div class="info 2">
                                    <h3>Last Update</h3>
                                    <h2>Lorem Ipsum</h2>
                                </div>
                            {% endcomment %}
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <div id="back_button">
        <p>Back</p>
    </div>
</div>
{% endblock app %}