PROD/v3/app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('members', views.listMembers, name='members'),
    path('active', views.listActiveMembers, name='activeMembers'),
    re_path(r'^repository/(?P<full_slug>(.*))', views.repository, name='files'),
    path('member/<str:username>/commits', views.listMemberCommits, name='memberCommits'),
    path('commits', views.commitList, name='commits'),
    path('issues', views.listAllIssues, name='issues'),
    path('issues/open', views.listOpenIssues, name='openIssues'),
    path('issues/closed', views.listClosedIssues, name='closedIssues'),
    path('branches', views.branches, name='branches'),
]

PROD/v3/gitnub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

PROD/v3/app/models.py
from django.contrib import admin
from django.db import models
from datetime import datetime
# Create your models here.

class LocalRepo(models.Model):
    url = models.CharField(max_length=255, unique=True)
    path = models.CharField(max_length=255, unique=True)
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Last Updated')

class ProjectMember(models.Model):
    ROLES = [
        ('Quality Assurance', 'Quality Assurance'),
        ('Development', 'Development'),
        ('Project Management', 'Project Management'),
        ('Architecture', 'Architecture'),
        ('Tests', 'Tests'),
        ('Requirements', 'Requirements'),
        ('Design', 'Design')
    ]
    CSS = [
        ('qa', 'Quality Assurance'),
        ('dev', 'Development'),
        ('pm', 'Project Management'),
        ('arch', 'Architecture'),
        ('tes', 'Tests'),
        ('req', 'Requirements'),
        ('des', 'Design')
    ]
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    email = models.CharField(max_length=255, unique=True)
    role = models.CharField(max_length=255, choices=ROLES)
    css = models.CharField(max_length=255, choices=CSS, null=True)

PROD/v3/app/forms.py
from typing import Dict
from django import forms
from django.db.models.fields import BLANK_CHOICE_DASH

class Picker(forms.Form):
    order = forms.ChoiceField(
        required=False, choices=[], label='',
        widget=forms.Select(attrs={'onchange': 'submit();'})
    )

    branch = forms.ChoiceField(
        required=False, choices=[], label='',
        widget=forms.Select(attrs={'onchange': 'submit();'})
    )

    def __init__(self, order, choices, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if order is None: del self.fields['order']
        else:
            self.fields['order'].choices = [
                item for item in order
            ]
        if choices is None: del self.fields
        else: 
            self.fields['branch'].choices = [
                ref if type(ref) == tuple else (ref, ref) for ref in choices 
            ]

PROD/v3/app/views.py
from django.http.request import HttpRequest
from django.shortcuts import redirect, render, HttpResponse
from pydriller import Repository
from git.repo import Repo
import logging

from app.models import ProjectMember
from . import gitlab
from .utils import getRepoPath, getRepository
from .forms import Picker

logger = logging.getLogger(__name__)
# Create your views here.
# Don't forget to route to your views in app/urls.py!

# route: / 
def index(request):
    return render(request, 'app/index.html')

# Req. 101 - Rodrigo Machado
# Helper for listMembers and listActiveMembers
def viewMembers(request: HttpRequest, template: str) -> HttpResponse:
    members = gitlab.getMembers()
    if members is None: return render(request, 'app/error.html', {'error': 'Algo correu mal'})
    members.sort(key=lambda x: x.name.lower())
    return render(request, template, {'members': members})

# Req. 101 - Rodrigo Machado
# route: /members
def listMembers(request: HttpRequest) -> HttpResponse:
    return viewMembers(request, 'app/members.html')


# Req. 101 - Rodrigo Machado
# route: /active
def listActiveMembers(request: HttpRequest) -> HttpResponse:
    # TODO only return people with commits
    return viewMembers(request, 'app/activeMembers.html')
    
# Req. 102 (modified)
# route: /member/<username>/commits
def listMemberCommits(request: HttpRequest, username: str) -> HttpResponse:
    try:
        repo = Repository(getRepoPath(gitlab.REPO_URL))
    except:
        return render(request, 'app/error.html', {'error': 'Branch does not exist!'})

    dbquery = ProjectMember.objects.filter(username=username)
    if not dbquery.exists():
        return render(request, 'app/error.html', {'message': 'Failed to retrieve user\'s email!'})
    
    member: ProjectMember = dbquery[0]
    email = member.email

    commits = []
    for commit in repo.traverse_commits():
        if commit.author.email == email: 
            commits.append(commit)
    
    context = {
        'member': member,
        'commits': commits,
    }
    return render(request, 'app/memberCommits.html', context)

# Req. 104 - Samuel Pires
# route: /repository
def repository(request, full_slug):
    #serve para no futuro existir possibilidade de abrirmos mais repositórios
    text = "Repository"
    owner = "Adriana02B"
    repo = "es-pl9"

    data, htmlFile, text = getRepository(full_slug, owner, repo)
    
    filename = ""
    paths = []
    md = False

    if full_slug:
        part = full_slug.split('/')
        if part[0] == '': part = part[1:]

        path = [x for x in part[:-1]]
        redirects = []
        for i in range(1, len(part)):
            redirect = ""
            for j in range(i):
                redirect += part[j]
                if j != i: redirect += '/'
            redirects.append(redirect)
        paths = zip(path, redirects)

        filename = part[-1]
        extension = filename.split('.')[-1]
        print(extension)
        if extension == 'md': md = True

    context = {
        'text': text,
        'data': data,
        'filename': filename,
        'paths': paths,
        'markdown': md,
    }
    return render(request, htmlFile, context)

# Req. 102 - Gonçalo Folhas
# route: /commits
def commitList(request):
    commit = []
    for element in Repository(getRepoPath(gitlab.REPO_URL), order = 'reverse').traverse_commits():
        query = ProjectMember.objects.filter(email=element.committer.email)
        css = None
        if query.exists(): css = query[0].css
        commit.append({
            'msg': element.msg,
            'author': element.committer.name,
            'date': element.committer_date,
            'css': css
        })
    return render(request, "app/commits.html", {'commits': commit})

# Req. 135 - David Leitão
# route: /issues
def listAllIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues()
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)
    
    context = {
        'text': 'All Issues',
        'issues': issues
    }
    return render(request, 'app/allIssues.html', context)

# Req. 135 - David Leitão
# route: /issues/open
def listOpenIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues(state='opened')
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)
    
    context = {
        'text': 'Open Issues',
        'issues': issues
    }
    return render(request, 'app/openIssues.html', context)
    
# Req. 135 - David Leitão
# route: /issues/closed
def listClosedIssues(request: HttpRequest) -> HttpResponse:
    issues = gitlab.getIssues(state='closed')
    if issues is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    issues.sort(key=lambda x: x.id, reverse=True)

    context = {
        'text': 'Closed Issues',
        'issues': issues
    }
    return render(request, 'app/closedIssues.html', context)

# Req. 162 - David Leitão
# route: /branches
def branches(request: HttpRequest) -> HttpResponse:
    branches = gitlab.getBranches()
    if branches is None: return render(request, 'app/error.html', {'message': 'Algo correu mal'})
    return render(request, 'app/branches.html', {'branches': branches})

PROD/v3/app/templates/app/activeMembers.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/activeMembers.css' %}">
{% endblock css %}

{% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a>Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}

{% block app %}
<div class="top-info">
    <div class="view">
        <a href="">GitNub ></a>
        <a href="">Project Information ></a>
        <a href="">Members</a>
    </div>

    <div class="order-by button">
        <span>Order by</span>
    </div>
</div>

<div class="members-list">
    {% for member in members %}
        <a href="{% url 'app:memberCommits' member.username %}">
            <div class="member {{ member.css }}">
                <div class="square-gitnub">
                    <div class="square">
                        <div class="circle"></div>
                    </div>
                </div>
                <div class="text">
                    <h4>{{ member.name }}</h2>
                    <h5>{{ member.role }}</h5>
                </div>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock app %}

PROD/v3/app/templates/app/allIssues.html
{% extends 'app/issues.html' %}

{% block state %}
<div class="issue-state">
    <div class="all select">
        <a>All</a>
    </div>

    <div class="open select">
        <a href="{% url 'app:openIssues' %}">Open</a>
    </div>

    <div class="closed select">
        <a href="{% url 'app:closedIssues' %}">Closed</a>
    </div>
</div>
{% endblock state %}

PROD/v3/app/templates/app/branches.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/branches.css' %}">
{% endblock css %}

{% block title %}Branches{% endblock title %}

{% block navbar %}
<div id="menu">
    <div class="select-page">
        <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a>Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}

{% block app %}
<div id="branches">
    <div id="nav_bar">
        <div class="left">
            <h2>GitNub > </h2>
            <h2 style="font-weight:500;"><a href="branches.html">Branches</a></h2>
        </div>

        <div class="right">
            <div class="search button"> <!-- SEARCH BAR -->
                <img src="{% static 'app/assets/search.svg' %}" alt="search"> 
                <input type="text" placeholder="Search">
            </div>

            <div class="name button"> <!-- ORDENAR POR NOME OU POR ULTIMO BRANCH ATUALIZADO-->
                <a href="#">Name</a>
            </div>
        </div>
    </div>

    <!-------------------- GRID DOS BRANCHES EXISTENTES ------------------>
    <div id="active-branches">
        <h1>Active Branches</h1>
        <div id="select-branch">
            {% for branch in branches  %}
            <div class="branch">
                <a>
                    <div class="icon">
                        <svg width="31" height="37" viewBox="0 0 31 37" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M12.9167 6.45701C12.917 7.94586 12.4029 9.38908 11.4614 10.5424C10.5199 11.6958 9.20877 12.4884 7.75001 12.7862V18.082H19.375C20.4027 18.082 21.3883 17.6737 22.115 16.947C22.8417 16.2203 23.25 15.2347 23.25 14.207V12.7862C21.6819 12.4661 20.2884 11.5751 19.3399 10.286C18.3913 8.99696 17.9552 7.40158 18.116 5.80921C18.2769 4.21684 19.0233 2.74093 20.2105 1.6676C21.3977 0.594273 22.9412 3.58774e-06 24.5417 3.58774e-06C26.1421 3.58774e-06 27.6856 0.594273 28.8728 1.6676C30.06 2.74093 30.8064 4.21684 30.9673 5.80921C31.1281 7.40158 30.692 8.99696 29.7435 10.286C28.7949 11.5751 27.4015 12.4661 25.8333 12.7862V14.207C25.8333 15.0551 25.6663 15.8949 25.3417 16.6785C25.0172 17.4621 24.5414 18.174 23.9417 18.7737C23.342 19.3734 22.6301 19.8492 21.8465 20.1737C21.0629 20.4983 20.2231 20.6653 19.375 20.6653H7.75001V23.3778C9.31814 23.6979 10.7116 24.5889 11.6601 25.878C12.6087 27.167 13.0448 28.7624 12.884 30.3548C12.7231 31.9472 11.9767 33.4231 10.7895 34.4964C9.60228 35.5697 8.05882 36.164 6.45834 36.164C4.85787 36.164 3.31441 35.5697 2.12719 34.4964C0.939973 33.4231 0.19358 31.9472 0.0327185 30.3548C-0.128143 28.7624 0.307985 27.167 1.25655 25.878C2.20512 24.5889 3.59854 23.6979 5.16668 23.3778V12.7862C3.96941 12.5418 2.86604 11.9627 1.98473 11.1163C1.10341 10.2699 0.480308 9.19078 0.187792 8.00435C-0.104725 6.81793 -0.0546529 5.57286 0.332193 4.41376C0.719039 3.25465 1.42678 2.22908 2.37323 1.45615C3.31967 0.683221 4.46597 0.194656 5.679 0.0471992C6.89202 -0.100258 8.12199 0.0994442 9.22605 0.623111C10.3301 1.14678 11.2629 1.97292 11.9162 3.00558C12.5695 4.03825 12.9164 5.23506 12.9167 6.45701Z"
                                fill="black" />
                        </svg>
                    </div>
                    <div class="text">
                        <h1>{{ branch.title }}</h1> <!-- Nome do branch -->
                        <div id="info">
                            <div class="info 1">
                                <h3>Last Update</h3>
                                <h2>{{ branch.ldate }}</h2>
                            </div>
                            <div class="info 2">
                                <h3>Updated by</h3>
                                <h2>{{ branch.lupdater }}</h2>
                            </div>

                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <!-------------------- BOTÃO BACK ------------------>
        <div id="back_button">
            <p>Back</p>
        </div>
    </div>
</div>
{% endblock app %}

PROD/v3/app/templates/app/closedIssues.html
{% extends 'app/issues.html' %}

{% block state %}
<div class="issue-state">
    <div class="all select">
        <a href="{% url 'app:issues' %}">All</a>
    </div>

    <div class="open select">
        <a href="{% url 'app:openIssues' %}">Open</a>
    </div>

    <div class="closed select">
        <a>Closed</a>
    </div>
</div>
{% endblock state %}

PROD/v3/app/templates/app/commits.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/commits.css' %}">
{% endblock css %}

{% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a>Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}
      
{% block app %}
<div class="top-info">
    <div class="view">
        <a href="">GitNub ></a>
        <a href="">Repository ></a>
        <a href="">Commits</a>
    </div>

    <div class="buttons">
        <div class="timeline button">
            <a>Timeline</a>
        </div>
    </div>
</div>

{% comment %} <h5 class="date">November 19th 2021</h5> {% endcomment %}
{% for commit in commits %}
<div class="day">
    <div class="commit">
        {% if commit.css %}
        <div class="circle {{ commit.css }}">
        {% else %}
        <div class="circle">
        {% endif %}
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>{{ commit.msg }}</h4>
            <p>{{ commit.author }}<span>{{ commit.date | date }}</span></p>
        </div>
    </div>
</div>
{% endfor %}


{% endblock app %}

PROD/v3/app/templates/app/issues.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/issues.css' %}">
{% endblock css %}    

{% block title %}GitNub{% endblock title %}

{% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a href="{% url 'app:members' %}">Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a>Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}
      
{% block app %}
<div class="top-info">
    <div class="view">
        <a>GitNub ></a>
        <a href="">Repository ></a>
        <a href="">Issues</a>
    </div>

    <div class="buttons">
        <div class="order-by button">
            <a href="">Order By</a>
        </div>
    </div>
</div>

{% block state %}{% endblock state %}

<div class="issues-list">

    {% for issue in issues %}
    <div class="issue">
        <div class="circle arch">
            <img src=" {% comment "TODO" %}{% endcomment %}">
        </div>
        <div class="text">
            <h4>{{ issue.title }}</h4>
            <p><span>created on </span><span>{{ issue.cd }} by </span>{{ issue.authorn }}</p>
            <p>updated xx hours ago</p>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock app %}

PROD/v3/app/templates/app/memberCommits.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/memberCommits.css' %}">
{% endblock css %}

{% block app %}
<div class="top-info">
    <div class="view">
        <a href="">Gitnub ></a>
        <a href="">Repository ></a>
        <a href="{% url 'app:activeMembers' %}">Active Members ></a>
        <a href="">{{ member.name }}</a>
    </div>

    <div class="buttons">
        <div class="back button">
            <a href="{% url 'app:activeMembers' %}">Back</a>
        </div>

        <div class="history button">
            <a href="">Commits</a>
        </div>
    </div>

</div>

{% for commit in commits %}
<div class="day">
    <div class="file">
        <div class="circle arch">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>{{ commit.msg }}</h4>
            <p>{{commit.author_date | date }}</p>
        </div>
    </div>
</div>
{% endfor %}

{% comment %} <h5 class="date">November 19th 2021</h5>

<div class="day">
    <div class="file">
        <div class="circle arch">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div>

<div class="day">
    <div class="file">
        <div class="circle req">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div>

<h5 class="date">November 18th 2021</h5>
<div class="day">
    <div class="file">
        <div class="circle arch">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div>

<div class="day">
    <div class="file">
        <div class="circle dev">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div>

<div class="day">
    <div class="file">
        <div class="circle req">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div>

<div class="day">
    <div class="file">
        <div class="circle des">
            <img src="img/Bernardo.jpeg">
        </div>
        <div class="text">
            <h4>This is a Commit</h4>
            <p>Author Name <span>xx hours ago</span></p>
        </div>
    </div>
</div> {% endcomment %}
{% endblock app %}

PROD/v3/app/templates/app/members.html
{% extends 'app/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/members.css' %}">
{% endblock css %}

{% block navbar %}
<div class="nav-bar">
    <img src="{% static 'app/assets/logo_fundosClaros.svg' %}" alt="logo">
    <div class="select-page">
        <ul class="project-info">
            <li class="main-selection">Project Information</li>
            <li class="hidden-selection">Activity</li>
            <li class="hidden-selection">Labels</li>
            <li class="hidden-selection"><a>Members</a></li>
        </ul>

        <ul class="repository">
            <li class="main-selection">Repository</li>
            <li class="hidden-selection"><a href="{% url 'app:files' '' %}">Files</a></li>
            <li class="hidden-selection"><a href="{% url 'app:commits' %}">Commits</a></li>
            <li class="hidden-selection"><a href="{% url 'app:branches' %}">Branches</a></li>
            <li class="hidden-selection">Tags</li>
            <li class="hidden-selection">Graph</li>
            <li class="hidden-selection">Compare</li>
            <li class="hidden-selection"><a href="{% url 'app:activeMembers' %}">Active Members</a></li>
        </ul>

        <ul class="issues">
            <li class="main-selection">Issues</li>
            <li class="hidden-selection"><a href="{% url 'app:issues' %}">Lists</a></li>
            <li class="hidden-selection">Boards</li>
            <li class="hidden-selection">Service Desk</li>
            <li class="hidden-selection">Milestones</li>
        </ul>

        <ul class="merge-requests">
            <li class="main-selection">Merge Requests</li>
        </ul>

        <ul class="ci-cd">
            <li class="main-selection">CI/CD</li>
        </ul>

        <ul class="security">
            <li class="main-selection">Security</li>
        </ul>

    </div>
</div>
{% endblock navbar %}

{% block app %}
<div class="top-info">
    <div class="view">
        <a href="">GitNub ></a>
        <a href="">Project Information ></a>
        <a href="">Members</a>
    </div>

    <div class="buttons">
        <div class="order-by button">
            <a>Order by</a>
        </div>
    </div>
</div>
<div class="members-list">

    {% for member in members %}
        <a>
            <div class="member {{ member.css }}">
                <div class="square-gitnub">
                    <div class="square">
                        <div class="circle"></div>
                    </div>
                </div>
                <div class="text">
                    <h4>{{ member.name }}</h2>
                    <h5>{{ member.role }}</h5>
                </div>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock app %}

PROD/v3/app/templates/app/openIssues.html
{% extends 'app/issues.html' %}

{% block state %}
<div class="issue-state">
    <div class="all select">
        <a href="{% url 'app:issues' %}">All</a>
    </div>

    <div class="open select">
        <a>Open</a>
    </div>

    <div class="closed select">
        <a href="{% url 'app:closedIssues' %}">Closed</a>
    </div>
</div>
{% endblock state %}