DEV/req102/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('example', views.template_example, name='example'),
    path('about', views.about, name='about'),
    path('commit', views.commit_list, name='commit'),
]

DEV/req102/gitnub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

DEV/req102/app/models.py
from django.contrib import admin
from django.db import models
from datetime import datetime
# Create your models here.

class LocalRepo(models.Model):
    url = models.CharField(max_length=255, unique=True)
    path = models.CharField(max_length=255, unique=True)
    timestamp = models.DateTimeField(auto_now=True, verbose_name='Last Updated')

DEV/req102/app/views.py
import logging
from django.shortcuts import render
from pydriller import Repository
from .utils import getRepoPath
from . import gitlab


logger = logging.getLogger(__name__)
# Create your views here.
# Don't forget to route to your views in app/urls.py!

# route: / 
def index(request):
    return render(request, 'app/index.html')

# route: /example
def template_example(request):
    text = "This is a Django template example"
    data = ["Try", "Out", "This", "For", "Loop"]
    return render(request, 'app/example.html', {'text': text, 'data': data})

# route: /about
def about(request):
    return render(request, 'app/about.html')

"""
def commit_list(request):
    #repo = Repo.clone_from('https://gitlab.com/Adriana02B/es-pl9/', 'C:/Users/35192/Documents/UNI/3rd Year/1st Semester/ES/new')
    # repo = Repo('/tmp/xxx')
    #commits = list(repo.iter_commits('master', max_count=5))
    repo_path = 'C:/Users/35192/Documents/UNI/3rd Year/1st Semester/ES/new'
    repo = Repo(repo_path)
    max = 23

    commits_list = list(repo.iter_commits('main', max_count=max, skip = 150))
    commit = []
    commit_author = []
    #print(commit_list)
    for i in range(max):
        info = "Author: " + str(commits_list[i].author) + " >  " + str(commits_list[i].message)
        commit.append(info)
        #commit_author.append(commits_list[i].author)

        #author = repo.git.show("-s", "--format=Author: %an <%ae>", commit.hexsha)
        #print(author)
    #commits = list(repo.iter_commits(rev=repo.branches["devel"]))
    #data = [{'name': str(c.author), 'email': c.author.email, 'msg': c.message} for c in commits]
    #for c in commits:
        #print("Commit Message: " + str(c.message))
    return render(request, "app/commit.html", {'text': "Commit List", 'data': commit})

    """



# to change -> path: GitNub>Repository>Commits

def commit_list(request):
    commit = []
    for element in Repository(getRepoPath(gitlab.REPO_URL), order = 'reverse').traverse_commits():
        commit.append({
            'msg': element.msg,
            'author': element.committer.name,
            'date': element.committer_date
        })
    return render(request, "app/commit.html", {'text': "Commit List", 'data': commit})

DEV/req102/app/templates/app/about.html
{% extends 'app/base.html' %}

{% block title %}About - GitNub{% endblock title %}

{% block app %}
<h1>WIP - Build about team here!</h1>
{% endblock app %}

DEV/req102/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GitNub{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/bootstrap.min.css' %}">
</head>
<body>
    <div class="wrapper">
        <div class="navbar navbar-light bg-light navbar-fixed-top shadow">
            <img class="navbar-brand" src="{% static 'app/logo.png' %}" alt="GitNub Logo" width="250px" height="auto">
        </div>
        <div class="fill">
            <div class="sidebar">
                <nav class="nav bg-light">
                    <a href="{% url 'app:index' %}" class="nav-link">Home</a>                   
                    <a href="{% url 'app:example' %}" class="nav-link">Example</a>
                    <a href="{% url 'app:about' %}" class="nav-link">About</a>
                    <a href="{% url 'app:commit' %}" class="nav-link">Commit</a>
                </nav>
            </div>
            <div id="app">{% block app %}{% endblock %}</div>
        </div>
    </div>
</body>
</html>

DEV/req102/app/templates/app/commit.html
{% extends "app/base.html" %}

{% block title %}Commit List - GitNub{% endblock %}

{% block app %}
<h1>{{ text }}</h1>

<ul>
    {% for commit in data %}
        <li>{{ commit.msg }} by {{ commit.author }} on {{ commit.date | date }}</li>
    {% endfor %}
</ul>
{% endblock %}

DEV/req102/app/templates/app/error.html
{% extends "app/base.html" %}

{% block app %}
<h1>Error</h1>
<p>{{ message }}</p>
{% endblock %}

DEV/req102/app/templates/app/example.html
{% extends "app/base.html" %}

{% block title %}Example - GitNub{% endblock %}

{% block app %}
<h1>{{ text }}</h1>

<ul>
    {% for sentence in data %}
        <li>{{ sentence }}</li>
    {% endfor %}
</ul>
{% endblock %}

DEV/req102/app/templates/app/index.html
{% extends "app/base.html" %}

{% block title %}Home - GitNub{% endblock %}

{% block app %}
<h1>Welcome to the development server!</h1>
{% endblock %}